exclude: [".gitignore", "README.md", "Rakefile", ]
highlighter: rouge
future: true

relative_permalinks: false

title : AI for Software Engineering
tagline:
author :
  name : Arie van Deursen
  github : serg-delft

url: "https://se.ewi.tudelft.nl/ai4se"

collections:
  tracks :
    output: true
    sort_by: track-id
  news :
    output: true
    sort_by: date